{% set version = "0.0.0" %} #TODO

package:
  name: cpp-app
  version: {{ version }}

source:
  git_url: https://github.com/lrobidou/fimpera

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
    - cmake

#  host:
#   -

#  run:
#   -

about:
  home: https://github.com/lrobidou/fimpera
  license: AGPL-3.0
  dev_url: https://github.com/lrobidou/fimpera
  doc_url: https://github.com/lrobidou/fimpera
